apiVersion: devops.k8s.io/v1
kind: Machine
metadata:
  labels:
    name: 10.248.224.210
    clusterName: cvm2-cluster
  name: 10.248.224.210
  namespace: cvm-admin
spec:
  clusterName: cvm2-cluster
  type: Baremetal
  machine:
    ip: 10.248.224.210
    port: 22
    username: root
    password: "UVK4AfcSuEQTK-LH-Lk1Fy"
  feature:
    hooks:
      installType: kubeadm
