annotations:
  category: Infrastructure
apiVersion: v1
appVersion: 1.6.1
description: Contour Ingress controller for Kubernetes
home: https://projectcontour.io
icon: https://bitnami.com/assets/stacks/contour/img/contour-stack-220x234.png
keywords:
- ingress
- envoy
- contour
name: contour
sources:
- https://github.com/projectcontour/contour
- https://github.com/envoyproxy/envoy
version: 1.1.5
