
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"
  creationTimestamp: null
  name: clustercredentials.devops.k8s.io
spec:
  group: devops.k8s.io
  names:
    kind: ClusterCredential
    listKind: ClusterCredentialList
    plural: clustercredentials
    singular: clustercredential
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ClusterCredential records the credential information needed to
          access the cluster.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          bootstrapToken:
            description: For kubeadm init or join
            type: string
          caCert:
            description: For connect the cluster
            format: byte
            type: string
          caKey:
            format: byte
            type: string
          certificateKey:
            description: For kubeadm init or join
            type: string
          certsBinaryData:
            additionalProperties:
              format: byte
              type: string
            type: object
          clientCert:
            description: For kube-apiserver X509 auth
            format: byte
            type: string
          clientKey:
            description: For kube-apiserver X509 auth
            format: byte
            type: string
          clusterName:
            type: string
          etcdAPIClientCert:
            format: byte
            type: string
          etcdAPIClientKey:
            format: byte
            type: string
          etcdCACert:
            description: For TKE in global reuse
            format: byte
            type: string
          etcdCAKey:
            format: byte
            type: string
          extData:
            additionalProperties:
              type: string
            type: object
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          kubeData:
            additionalProperties:
              type: string
            type: object
          manifestsData:
            additionalProperties:
              type: string
            type: object
          metadata:
            type: object
          tenantID:
            type: string
          token:
            description: For kube-apiserver token auth
            type: string
        required:
        - clusterName
        - tenantID
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
